server:
 port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobboarddb
    username: postgres           # replace if you use a different user
    password: admin              # replace with your actual password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: MySuperSecretKeyMustBe32BytesLong!

logging:
  level:
    root: INFO
    com.example.service: DEBUG
    org.springdoc: DEBUG
    org.springframework.web: DEBUG

#server:
#  port: 8082
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/jobboarddb
#    username: jobboarduser           # ✅ the user you created in psql
#    password: strongpassword         # ✅ the password you set in psql
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#jwt:
#  secret: MySuperSecretKeyMustBe32BytesLong!
#
#logging:
#  level:
#    root: INFO
#    com.example.service: DEBUG
#    org.springdoc: DEBUG
#    org.springframework.web: DEBUG

